name: Release
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PRIME_REGISTRY: ${{ secrets.PRIME_REGISTRY }}
  PRIME_REGISTRY_USERNAME: ${{ secrets.PRIME_REGISTRY_USERNAME }}
  PRIME_REGISTRY_PASSWORD: ${{ secrets.PRIME_REGISTRY_PASSWORD }}
on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # write is needed for:
      # - OIDC for cosign's use in ecm-distro-tools/publish-image.
      # - Read vault secrets in rancher-eio/read-vault-secrets.
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Parse target tag
      run: |
        TARGET=${{ github.ref_name }}
        echo "TAG=${TARGET#v}" >> $GITHUB_ENV
    - name: Publish public manifest
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: prometheus-exporter
        tag: ${{ env.TAG }}
        platforms: linux/amd64,linux/arm64

        public-registry: docker.io
        public-repo: holyspectral
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_PASSWORD }}
    - name: Publish prime manifest
      uses: rancher/ecm-distro-tools/actions/publish-image@master
      with:
        image: neuvector-prometheus-exporter
        tag: ${{ env.TAG }}
        platforms: linux/amd64,linux/arm64

        prime-registry: ${{ env.PRIME_REGISTRY }}
        prime-repo: holyspectral
        prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
        prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}
